services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "8080:8080"
      - "5173:5173"
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: budgetbuddy
      POSTGRES_PASSWORD: password
      POSTGRES_DB: budgetbuddy
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U budgetbuddy"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
